### ISSUE TITLE
[FEATURE] Open to TypeScript type definitions?

### ISSUE THREAD

**Issue by trevor-scheer** [npm/make-fetch-happen#20]
# What / Why
👋 We over at Apollo [just introduced](https://github.com/apollographql/apollo-server/pull/3783) `make-fetch-happen` into our federation gateway and would love to have the TS typings available.

Are the maintainers open to a PR which adds the definitions to the package itself, or would you prefer they end up in `DefinitelyTyped`? At some point, I'll likely do one or the other, with my preference being the former - just wanted to hear your thoughts before I do so.

Thanks!

**Comment by abernix** [comment]
I've gone ahead and opened this on DefinitelyTyped with, I think, a couple improvements inspired mostly by their contribution rules (e.g., recursivity of `defaults()`, tests!): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50339.  Reviews from qualified reviewers very much welcome!

**Comment by trevor-scheer** [comment]
These type definitions are now live on DT via `@types/make-fetch-happen` thanks to @abernix 's PR! Would still love to see these land in the repo itself, so going to leave this issue and the related PR #31 open.

**Comment by isaacs** [comment]
As a general rule, we don't accept type definitions in PRs because we have no way of ensuring that they don't fall out of sync with the code they describe, short of moving the npm cli to TypeScript, which we have no plans to do at this time. Until these sorts of PRs come along with a test that ensures that the type definitions are accurate and comprehensive, and can highlight divergence in CI, it is not a good idea to accept them.
