### ISSUE TITLE
improve and extend caching semantics

### ISSUE THREAD

**Issue by nlf** [npm/make-fetch-happen#48]
today, make-fetch-happen handles some caching semantics reasonably well but has a flaw in that cached indexes can grow unbounded. we're also sending more requests (and downloading more data) than is necessary when we know the expected integrity of the content we're requesting.

we need to make the following modifications to improve the caching experience for npm

- [x] reduce the request and response headers stored in the index metadata to only those necessary for caching purposes
- [x] when an expected integrity is provided, disregard http caching semantics and ask cacache for the content directly. if cacache doesn't have the content, only then should we send the request
- [x] when sending a request to revalidate a cached response (typically due to max-age having expired), after receiving a 304 response and writing the new index, we must remove the original index matching our request

**Comment by isaacs** [comment]
Just to clarify:

>  reduce the request and response headers stored in the index metadata to only those necessary for caching purposes

Should be "to only those that can affect the response we receive".  If we `accept: application/json`, then the server could send a different response than `accept: text/plain`, for example.  Basically, first step should be to go through the known headers in [this list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Index) and flag all the ones where we'd expect to get a different response based on that request header.

One consideration: authorization headers.  If you send an authorization header, you might get a response rather than a 403.  But caching auth tokens is kind of a terrible thing to do.  And so is caching an authorized response and then serving it back from cache if the request is _not_ authorized.  So basically, these need to be included in the hash used in the key name, but _not_ included in the metadata saved along with the key in the index file.

>  when an expected integrity is provided, disregard http caching semantics and ask cacache for the content directly. if cacache doesn't have the content, only then should we send the request

Again, auth may bite us a little bit here.

Let's say I make an authed request for `/foo`, and get digest `sha512-deadbeef`.  Then later, I'm not authed, and I make a request for the same resource, this time with an expected shasum.  We can take a couple of approaches to this:

- You have the shasum, so you get the bits.  (So now, sharing the shasum is no longer safe, because it can make npm bypass auth, which is bad, but not _very_ bad, because it'd only happen if the content is already on your machine at that location.)
- If we have auth, we don't do the key bypass check for contents.  (So, not much value to this feature, then, because npm pretty much always sends an auth token if it has one for that server.)

My gut is that the first option is probably fine, but we need to be clear that specifying a shasum may result in bits being loaded from cache that _would have_ resulted in a 4xx with the request actually being made.

**Comment by isaacs** [comment]
> when an expected integrity is provided, disregard http caching semantics and ask cacache for the content directly. if cacache doesn't have the content, only then should we send the request

Also, we should write the new index to that content, so that a subsequent matching request that _doens't_ have the integrity will benefit from having it cached.

**Comment by nlf** [comment]
after discussing with a few security minded folk, ignoring auth for our purposes is fine. we do not consider the cache to be shared, since it isn't meant to leave a single user's home directory, so disregarding auth for caching purposes is acceptable. if someone gets a hold of your cache directory it wouldn't be that hard for them to track down the hash and the file anyway, so there's no real reason to go out of our way to refuse to handle authed requests
