### ISSUE TITLE
[BUG] maxSockets option not respected for proxied connections

### ISSUE THREAD

**Issue by silverwind** [npm/make-fetch-happen#59]
# What / Why
The [maxSocket](https://github.com/npm/make-fetch-happen#--optsmaxsockets) option does not appear to be respected in case a HTTPS proxy is in use, e.g. on a typical `npm install`, a proxy may be bombarded with hundrets of parallel requests, potentially overloading it.

I think the issue is that this module passes `maxSockets` to `https-proxy-agent` [via the constructor](https://github.com/npm/make-fetch-happen/blob/2d978bebff67f272f9a0bcf6f1c786a5b275ddd4/lib/agent.js#L175), but that module [does not support](https://github.com/TooTallNate/node-https-proxy-agent#new-httpsproxyagentobject-options) such a constructor option. It may be possible to set it via `agent.maxSockets` after agent instantiation, see https://github.com/TooTallNate/node-https-proxy-agent/issues/105.

## When
When a `HTTPS_PROXY` environment variable is set to a proxy, meaning `https-proxy-agent` is being used.

## Where
On `npm install`

### Current Behavior
Proxy is being bombarded with unbound number of parallel requests

### Steps to Reproduce
- Configure a local HTTPS proxy on port 3128
- Run `HTTPS_PROXY=https://localhost:3128 npm install` on a sizeable project
- Observer the proxy's log

### Expected Behavior
Parallel requests to the proxy limited to 15 (the current default)

**Comment by nlf** [comment]
after some investigation, setting the `maxSockets` outside of the constructor has no effect. `agent-base`, the module all three of `http-proxy-agent`, `https-proxy-agent` and `socks-proxy-agent` are built on does not respect the setting at all.

**Comment by huangyq23** [comment]
`hpagent`'s approach of extending Node's own `http` and `https` agent module seems to be a more reasonable implementation than `http-proxy-agent`/`https-proxy-agent`/`socket-proxy-agent`'s approach of a separate `agent-base`.

It does not seem the maintainer of  `http-proxy-agent`/`https-proxy-agent`/`socket-proxy-agent` plan to add keep alive support anytime soon. 
https://github.com/TooTallNate/node-agent-base/issues/5
https://github.com/TooTallNate/node-socks-proxy-agent/issues/68
https://github.com/TooTallNate/node-http-proxy-agent/issues/23

Proxy server are heavily used in corporate networking environment. Without KeepAlive and connection pooling, it is almost always going to create a DoS.

https://github.com/npm/make-fetch-happen/blob/ea711108e53f04d848084db51477b5a24d176884/lib/agent.js#L172-L174

I wonder if `make-fetch-happen` should switch to `hpagent` or try to make the underlying agent for proxy configurable so that we can plug in alternative implementation.

**Comment by silverwind** [comment]
I think it`s worth switching to `hpagent` for HTTP and HTTPS. I don't think it can do Socks, so `socks-proxy-agent` will probably have to remain.

**Comment by lukekarrys** [comment]
This should be fixed by the latest version of `@npmcli/agent@2.1.0`. That package still uses `https-proxy-agent` but only as a way to get a socket connection. There is only a single agent (and HttpsAgent) supplied by `@npmcli/agent` which respect `maxSockets`.

@silverwind if you are still seeing issues, please open a new issue (or i can transfer this one and reopen it) over at https://github.com/npm/agent/issues/new/choose
