### ISSUE TITLE
[QUESTION] Caching Additional End-to-End Response Headers

### ISSUE THREAD

**Issue by tompahoward** [npm/make-fetch-happen#62]
Is there a reason only a subset of [End-to-End Response Headers](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.5.1) are cached?

I can see from https://github.com/npm/make-fetch-happen/blob/43514f651e5e3a6420de46756386f414f1cb4c6c/lib/cache/entry.js#L34 and https://github.com/npm/make-fetch-happen/blob/43514f651e5e3a6420de46756386f414f1cb4c6c/lib/cache/entry.js#L92 that only the following response headers are stored:

-   `cache-control`
-   `content-encoding`
-   `content-language`
-   `content-type`
-   `date`
-   `etag`
-   `expires`
-   `last-modified`
-   `location`
-   `pragma`
-   `vary`

But if I'm reading the spec correctly, only the following headers are considered "hop-by-hop" headers and should not be stored:

- `Connection`
- `Keep-Alive`
- `Proxy-Authenticate`
- `Proxy-Authorization`
- `TE`
- `Trailers`
- `Transfer-Encoding`
- `Upgrade`

> Hop-by-hop headers, which are meaningful only for a single transport-level connection, and are not stored by caches or forwarded by proxies.

but otherwise

> End-to-end headers, which are transmitted to the ultimate recipient of a request or response. End-to-end headers in responses MUST be stored as part of a cache entry and MUST be transmitted in any response formed from a cache entry.

Am I reading the code wrong, reading the spec wrong, or is there a reason why only those headers are stores, or should I submit a pull request not to store "hop-by-hop" headers and store all "end-to-end" headers?

PS the question template had all the sections marked as n/a, so I assume there's no specific format for questions; I hope that's OK

**Comment by wraithgar** [comment]
The comment above that block kind of describes why we have only a subset there.  It could probably be more elaborate.

The `age` header for instance is one that if we stored it, would cause our cache to be non-functioning i.e. it would always think the content was stale.  There are also things like the `cf-ray` header that Cloudflare returns that would cause the same behavior.

[The comment from before this refactor](
https://github.com/npm/make-fetch-happen/blob/4f3384738fe02a993b0e9f94f182ea5831975bf7/cache.js#L15-L18) also explains that there are security issues in storing all headers as well as general space considerations.

```javascript
// some headers should never be stored in the cache, either because
// they're a security footgun to leave lying around, or because we
// just don't need them taking up space.
// set to undefined so they're omitted from the JSON.stringify
```

In the end, an allow list is the only thing that doesn't eventually break our cache. This module strives to only store the headers we know are needed, and nothing more.

**Comment by tompahoward** [comment]
Thanks @wraithgar . Based on https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.2.3 , it looks like `age` is a special case. i.e. it's neither a hop-by-hop header or an end-to-end header; I'd call it a cache-to-end header.

I get that it only makes sense to store certain _request_ headers and not others, like `authorization` and `cf-ray` (security footgun etc), but how do you know what response headers are and aren't needed?

Here's my problem: the service I'm calling sends [RFC8288](https://datatracker.ietf.org/doc/html/rfc8288) `link` response headers, which the client then uses to `GET` related resources.  When the response is served from make-fetch-happen's cache, the client can't `GET` any related resources.

Would a PR that provides a configuration option to tell make-fetch-happen to store more response headers be welcome? 

I was thinking something like this

```
const fetch = require('make-fetch-happen').defaults({
  additionalResponseHeaders: ['link']
})
```

thoughts?

**Comment by wraithgar** [comment]
I think having a way to add additional headers makes sense, but also worry about the opaqueness of the current approach, which is a remnant of the provenance of this module itself i.e. it was for the npm cli interacting solely with the npm registry.  [npm-registry-fetch](https://github.com/npm/npm-registry-fetch) is intended to be the place where we bake in the assumptions we have for npm registries themselves, so ultimately that list should live there.

How do you feel about exporting those two lists somewhere as part of `make-fetch-happen`, and then requiring the 'additional cached response headers' and 'additional cached request headers' options require that you pass in the entirety of what you want cached?  This way we don't have to, someday in the future, worry about *omitting* things from those defaults if that becomes needed.  Your use case would then look something like

```javascript
const mfh = require('mfh')
const fetch = mfh.defaults({
  cachedResponseHeaders: ['link', ...mfh.CACHED_RESPONSE_HEADERS]
})
```

I'm just thinking this through here, and don't know if it makes more sense to require that anyone setting the cachedResponseHeaders wholly generate the list without needing the existing defaults.

In any case I do think that having a way for defining at least the response headers to be cached makes sense.  I would hesitate to do the same for request headers unless it became something somebody absolutely needed because of the security issues involved there (auth headers being the main concern, best not to even let someone make that mistake if we don't have to).

What do you think?

**Comment by wraithgar** [comment]
The alternative is that we simply add `Link` to that hard coded list.  It's certainly not the most scalable solution (we have to make this decision every time there's a header someone needs for their use case) but `Link` is a pretty easy decision at least if we wanted to add it.
